# Thomas Wolf
# 2/8/23
# Intro

import turtle

turtle.bgcolor('black')
turtle.shape('turtle')
turtle.color('blue')
turtle.penup()
turtle.goto(-300, 0)
turtle.pendown()  # T
turtle.left(90)
turtle.forward(150)
turtle.left(90)
turtle.forward(75)
turtle.left(180)
turtle.forward(150)
turtle.color('orange')  # h
turtle.right(90)
turtle.forward(150)
turtle.right(180)
turtle.forward(75)
turtle.right(90)
turtle.forward(75)
turtle.right(90)
turtle.forward(75)
turtle.penup()
turtle.left(90)
turtle.forward(75)
# turtle.pendown()
# turtle.color('purple')  # O
# turtle.circle(50)
# turtle.penup()
# turtle.forward(75)
# turtle.pendown()
# turtle.color('green')  # M
# turtle.left(90)
# turtle.forward(125)
# turtle.backward(35)
# turtle.right(90)
# turtle.forward(50)
# turtle.right(90)
# turtle.forward(90)
# turtle.backward(90)
# turtle.left(90)
# turtle.forward(50)
# turtle.right(90)
# turtle.forward(90)
# turtle.left(90)
# turtle.penup()
# turtle.forward(75)
# turtle.color('red')  # A
# turtle.pendown()
# turtle.circle(50)
# turtle.penup()
# turtle.left(90)
# turtle.forward(75)
# turtle.right(90)
# turtle.forward(43)
# turtle.pendown()
# turtle.right(65)
# turtle.forward(75)
# turtle.left(65)
# turtle.penup()
# turtle.forward(75)
# turtle.left(90)
# turtle.forward(70)
# turtle.right(30)
# turtle.color('yellow')  # S
# turtle.pendown()
# for num in range(30):
#     turtle.left(10)
#     turtle.forward(5)
# for num in range(30):
#     turtle.right(10)
#     turtle.forward(5)
# turtle.penup()
# turtle.goto(1000, 1000)
# while True:
#     turtle.bgcolor('blue')
#     turtle.bgcolor('orange')
#     turtle.bgcolor('purple')
#     turtle.bgcolor('green')
#     turtle.bgcolor('red')
#     turtle.bgcolor('yellow')
